spring.config.import=optional:classpath:application-local.properties
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.data.rest.base-path=/api

## issuer url must ends with "/"
okta.oauth2.issuer=https://dev-6qtr30vk60x15j0l.us.auth0.com/
okta.oauth2.client-id=Iw3lRLeJLaulMVcfvHW5ePkUEnKqd3kS
okta.oauth2.groupsClaim=https://salaheddine-library.com/roles
okta.oauth2.audience=http://localhost:8080

spring.profiles.active=dev

